Remove k8s client validity check from pkg/flags
With the addition of `cli/pkg/cli/prerun` to `pkg/cmd/bundle` in #1575
the validity of the Kubernetes REST client is checked via invocation of
`pkg/flags.InitParams` where it fails with:

```
Error: Couldn't get kubeConfiguration namespace: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

A valid Kuberenets configuration should not be supplied for `tkn bundle`
commands, so this removes verifying that the Kuberenets configuration is
valid from `pkg/flags.InitParams`. Seems that the same check for
validity is preformed whenever invocation of `pkg/cli.Params.Clients` is
used regardless, so having a check in the `InitParams` needlessly
enforces the requirement of valid Kubernetes configuration.